// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 alibaba/open-code-review Contributors
//
// Ported from internal/model/review.go at c35ddd7223f2b5540ce03aa43c9a25ef643fca27.
// Modifications are distributed as part of pi-reviewer under
// GPL-3.0-or-later;
// see LICENSES/Apache-2.0.txt and THIRD_PARTY_NOTICES.md.

/**
 * LlmComment represents a code review comment generated by the LLM.
 * Mirrors Go's `model.LlmComment`. Field names are camelCase; JSON keys
 * remain snake_case for compatibility with `json:"..."` tags.
 */
export interface LlmComment {
  /** Repository-relative path, e.g. "a.go". Mirrors `Path` json:"path". */
  path: string;
  /** Human-readable review content. Mirrors `Content` json:"content". */
  content: string;
  /**
   * Suggested replacement code. Mirrors `SuggestionCode`
   * json:"suggestion_code,omitempty".
   */
  suggestionCode?: string;
  /**
   * Existing code referenced by the comment. Mirrors `ExistingCode`
   * json:"existing_code,omitempty".
   */
  existingCode?: string;
  /** 1-based start line, 0 means unspecified. Mirrors `StartLine` json:"start_line". */
  startLine?: number;
  /** 1-based end line, 0 means unspecified. Mirrors `EndLine` json:"end_line". */
  endLine?: number;
  /** Model thinking text. Mirrors `Thinking` json:"thinking,omitempty". */
  thinking?: string;
  /**
   * Category: bug, security, performance, maintainability, test, style,
   * documentation, other. Mirrors `Category` json:"category,omitempty".
   */
  category?: string;
  /**
   * Severity: critical, high, medium, low. Mirrors `Severity`
   * json:"severity,omitempty".
   */
  severity?: string;
}

/** Raw JSON shape for LlmComment matching Go tags. */
export interface LlmCommentJson {
  path: string;
  content: string;
  suggestion_code?: string;
  existing_code?: string;
  start_line: number;
  end_line: number;
  thinking?: string;
  category?: string;
  severity?: string;
}

/**
 * CodeReviewResult holds raw LLM-generated review suggestion for a code segment.
 * Mirrors Go's `model.CodeReviewResult`.
 */
export interface CodeReviewResult {
  /** Relevant file; mirrors `RelevantFile` json:"relevant_file". */
  relevantFile: string;
  /** Suggestion content; mirrors `SuggestionContent` json:"suggestion_content". */
  suggestionContent: string;
  /** Existing code; mirrors `ExistingCode` json:"existing_code". */
  existingCode: string;
  /** Suggestion code; mirrors `SuggestionCode` json:"suggestion_code". */
  suggestionCode: string;
}

/** Raw JSON shape for CodeReviewResult matching Go tags. */
export interface CodeReviewResultJson {
  relevant_file: string;
  suggestion_content: string;
  existing_code: string;
  suggestion_code: string;
}

// ---------------------------------------------------------------------------
// Constructors
// ---------------------------------------------------------------------------

export function createLlmComment(partial: Partial<LlmComment> & { path: string; content: string }): LlmComment {
  const c: LlmComment = {
    path: partial.path,
    content: partial.content,
  };
  if (partial.suggestionCode !== undefined) c.suggestionCode = partial.suggestionCode;
  if (partial.existingCode !== undefined) c.existingCode = partial.existingCode;
  if (partial.startLine !== undefined) c.startLine = partial.startLine;
  if (partial.endLine !== undefined) c.endLine = partial.endLine;
  if (partial.thinking !== undefined) c.thinking = partial.thinking;
  if (partial.category !== undefined) c.category = partial.category;
  if (partial.severity !== undefined) c.severity = partial.severity;
  return c;
}

export function createCodeReviewResult(partial: Partial<CodeReviewResult> = {}): CodeReviewResult {
  return {
    relevantFile: partial.relevantFile ?? "",
    suggestionContent: partial.suggestionContent ?? "",
    existingCode: partial.existingCode ?? "",
    suggestionCode: partial.suggestionCode ?? "",
  };
}

// ---------------------------------------------------------------------------
// JSON mapping — keep snake_case keys compatible with Go
// ---------------------------------------------------------------------------

export function llmCommentToJson(c: LlmComment): LlmCommentJson {
  const j: LlmCommentJson = {
    path: c.path,
    content: c.content,
    start_line: c.startLine ?? 0,
    end_line: c.endLine ?? 0,
  };
  if (c.suggestionCode !== undefined && c.suggestionCode !== "") j.suggestion_code = c.suggestionCode;
  if (c.existingCode !== undefined && c.existingCode !== "") j.existing_code = c.existingCode;
  if (c.thinking !== undefined && c.thinking !== "") j.thinking = c.thinking;
  if (c.category !== undefined && c.category !== "") j.category = c.category;
  if (c.severity !== undefined && c.severity !== "") j.severity = c.severity;
  // Mimic Go's omitEmpty: delete empty optional keys so output matches Go
  if (j.suggestion_code === undefined) delete (j as unknown as Record<string, unknown>)["suggestion_code"];
  if (j.existing_code === undefined) delete (j as unknown as Record<string, unknown>)["existing_code"];
  if (j.thinking === undefined) delete (j as unknown as Record<string, unknown>)["thinking"];
  if (j.category === undefined) delete (j as unknown as Record<string, unknown>)["category"];
  if (j.severity === undefined) delete (j as unknown as Record<string, unknown>)["severity"];
  return j;
}

export function llmCommentFromJson(j: LlmCommentJson): LlmComment {
  const c: LlmComment = {
    path: j.path ?? "",
    content: j.content ?? "",
  };
  if (typeof j.suggestion_code === "string") c.suggestionCode = j.suggestion_code;
  if (typeof j.existing_code === "string") c.existingCode = j.existing_code;
  if (typeof j.thinking === "string") c.thinking = j.thinking;
  if (typeof j.category === "string") c.category = j.category;
  if (typeof j.severity === "string") c.severity = j.severity;
  if (typeof j.start_line === "number" && j.start_line !== 0) c.startLine = j.start_line;
  else if (typeof j.start_line === "number" && j.start_line === 0) c.startLine = 0;
  if (typeof j.end_line === "number" && j.end_line !== 0) c.endLine = j.end_line;
  else if (typeof j.end_line === "number" && j.end_line === 0) c.endLine = 0;
  // Preserve Go semantics: 0 means unspecified; keep optional but allow 0
  // For strict optional behavior, callers can treat 0 as undefined.
  if (c.startLine === 0) {
    // keep as 0 to mirror Go round-trip; callers may normalize
  }
  if (c.endLine === 0) {
    // same
  }
  return c;
}

export function codeReviewResultToJson(r: CodeReviewResult): CodeReviewResultJson {
  return {
    relevant_file: r.relevantFile,
    suggestion_content: r.suggestionContent,
    existing_code: r.existingCode,
    suggestion_code: r.suggestionCode,
  };
}

export function codeReviewResultFromJson(j: CodeReviewResultJson): CodeReviewResult {
  return {
    relevantFile: j.relevant_file ?? "",
    suggestionContent: j.suggestion_content ?? "",
    existingCode: j.existing_code ?? "",
    suggestionCode: j.suggestion_code ?? "",
  };
}

export function parseLlmCommentFromUnknown(value: unknown): LlmComment | null {
  if (typeof value !== "object" || value === null || Array.isArray(value)) return null;
  const obj = value as Record<string, unknown>;
  const pathVal = obj["path"];
  const contentVal = obj["content"];
  if (typeof pathVal !== "string" || typeof contentVal !== "string") return null;
  const c: LlmComment = {
    path: pathVal,
    content: contentVal,
  };
  if (typeof obj["suggestion_code"] === "string") c.suggestionCode = obj["suggestion_code"] as string;
  if (typeof obj["existing_code"] === "string") c.existingCode = obj["existing_code"] as string;
  if (typeof obj["thinking"] === "string") c.thinking = obj["thinking"] as string;
  if (typeof obj["category"] === "string") c.category = obj["category"] as string;
  if (typeof obj["severity"] === "string") c.severity = obj["severity"] as string;
  if (typeof obj["start_line"] === "number") c.startLine = obj["start_line"] as number;
  else if (typeof obj["startLine"] === "number") c.startLine = obj["startLine"] as number;
  if (typeof obj["end_line"] === "number") c.endLine = obj["end_line"] as number;
  else if (typeof obj["endLine"] === "number") c.endLine = obj["endLine"] as number;
  return c;
}

export function parseCodeReviewResultFromUnknown(value: unknown): CodeReviewResult {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    return createCodeReviewResult();
  }
  const obj = value as Record<string, unknown>;
  return {
    relevantFile:
      typeof obj["relevant_file"] === "string" ? (obj["relevant_file"] as string) : "",
    suggestionContent:
      typeof obj["suggestion_content"] === "string"
        ? (obj["suggestion_content"] as string)
        : "",
    existingCode: typeof obj["existing_code"] === "string" ? (obj["existing_code"] as string) : "",
    suggestionCode:
      typeof obj["suggestion_code"] === "string" ? (obj["suggestion_code"] as string) : "",
  };
}

export function stringifyLlmComment(c: LlmComment): string {
  return JSON.stringify(llmCommentToJson(c));
}

export function parseLlmCommentJson(json: string): LlmComment | null {
  const raw: unknown = JSON.parse(json) as unknown;
  return parseLlmCommentFromUnknown(raw);
}

export function stringifyCodeReviewResult(r: CodeReviewResult): string {
  return JSON.stringify(codeReviewResultToJson(r));
}

export function parseCodeReviewResultJson(json: string): CodeReviewResult {
  const raw: unknown = JSON.parse(json) as unknown;
  return parseCodeReviewResultFromUnknown(raw);
}
